Repository Azure/Mission-Critical-Online, pull requests merged in 2022-02, with the labels that each got.

#68 Update vue and vue-router
  src/app/AlwaysOn.UI/package-lock.json
  src/app/AlwaysOn.UI/package.json
  src/app/AlwaysOn.UI/src/App.vue
  src/app/AlwaysOn.UI/src/components/ItemPage.vue
  src/app/AlwaysOn.UI/src/components/MainPage.vue
  src/app/AlwaysOn.UI/src/main.js
Labels: javascript

#74 Remove AKS AutoUpgrade Preview instructions
  src/infra/workload/README.md
Labels: Cleanup

#91 Create dedicated branch for the run
  .github/workflows/updateDependabot.yml
Labels: enhancement

#102 add missing link back to docs root
  docs/reference-implementation/OpProcedures-Operational-Procedures.md
Labels: documentation

#155 Add additional comments for `stampLocation` value changes
  .ado/pipelines/config/variables-values-e2e.yaml
  .ado/pipelines/config/variables-values-int.yaml
  .ado/pipelines/config/variables-values-prod.yaml
Labels: documentation

#152 Move locust config to central config file
  .ado/pipelines/azure-deploy-locust.yaml
  .ado/pipelines/config/configuration.yaml
  .ado/pipelines/templates/stages-full-release.yaml
  .ado/pipelines/templates/stages-locust.yaml
Labels: enhancement

#161 Note about deleting Cosmos manually
  docs/reference-implementation/Troubleshooting.md
Labels: documentation
